spring:
  application:
    name: chat
  datasource:
    url: jdbc:mysql://localhost:3306/chat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1 # Redis服务器地址
      port: 6379 # Redis服务器端口
      password: # Redis服务器密码，如果有的话
      database: 0 # 使用的数据库索引
      jedis:
        pool:
          max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接
          max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）

mybatis-plus:
  global-config:
    # 关闭启动时banner
    banner: false
  mapper-locations: classpath:/mapper/**.xml
  type-aliases-package: com.lycodeing.chat.domain
  configuration:
    # 开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true


netty:
  # 端口
  port: 9000
  # 最大内容长度
  maxContentLength: 65536
  # websocket路径
  websocketPath: /chat
  # 心跳超时时间
  idleTimeout: 60
security:
  white-list:
    - /chat/login
    - /chat/register
    - /chat/logout
    - /chat/heartbeat
