spring:
  application:
    name: chat
  datasource:
    url: jdbc:mysql://localhost:3306/chat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root


mybatis-plus:
  global-config:
    # 关闭启动时banner
    banner: false
  mapper-locations: classpath:/mapper/**.xml
  type-aliases-package: com.lycodeing.chat.domain
  configuration:
    # 开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true